### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by cabralmartin** [auth0/auth0-ab#3]
- [x] Replicate cdn publication script such as auth0-metrics
- [x] Fix tests. (Tests are not running and those that run are not passing)
- [x] Remove the `test_harness.html` in favor or `zuul --local`
- [x] Replace auth0-website ab-module with this one
- [x] Publish 0.1.0 version on cdn
- [x] Move load script to the AB/Testing repository (ala metrics)
- [x] Add a minify task for the load script
- [x] Create a simple node service to deliver auth0’s experiments from a private github repository
  - [x] Parse experiment yamls files
  - [x] Parse js operations referenced in the yaml files
  - [x] Experiments with the weight on the root `experiment` object must propagate its weight to its variants
  - [x] Variants with no action (i.e. those that will not apply any changes) need to have an empty property/action
  - [x] Add a task to check sanity of the yaml files
  - [x] Run a linter on the JS files to detect possible issues
- [x] Implement updates to the lib so @mgonto’s MVP examples work
  - [x] Updated middleware to only run the matching experiments for the current route
  - [x] Add support for blog (we have no pagejs here, so we need to work with the standalone version of the library)
  - [x] Send jQuery object to the middleware context (variants may depend on this)
- [x] Deploy experiments service (sync with ops. we want High Availability for the deployment)
- [x] Update AB/Testing repository README with latest changes
- [x] Update ab-experiments repository README with how the syntax work and whats expected from the .yaml files (aside of the information required on how to run the service)

**Comment by cristiandouce** [comment]
:+1:

**Comment by cabralmartin** [comment]
https://github.com/auth0/auth0-ab/releases/tag/v1.0.0
